# swagger.yml

openapi: 3.0.0
info:
  title: "Movie Flask REST API"
  description: "An API about movies"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Movie:
      type: "object"
      required:
        - name
        - cast
      properties:
        name:
          type: "string"
        cast:
          type: "array"
        genres:
          type: "array"
  parameters:
    name:
      name: "name"
      description: "The movie name to lookup"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /movies:
    get:
      operationId: "movies.read_all"
      tags:
        - Movies
      summary: "Read the list of movies"
      responses:
        "200":
          description: "Successfully read the movie list"
    post:
      operationId: "movies.create"
      tags:
        - Movies
      summary: "Create a movie"
      requestBody:
          description: "Movie to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "movie"
                $ref: "#/components/schemas/Movie"
      responses:
        "201":
          description: "Successfully created movie"
  /movies/{name}:
    get:
      operationId: "movies.read_one"
      tags:
        - Movies
      summary: "Read one movie"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully read movie"