# swagger.yml

openapi: 3.0.0
info:
  title: "Coffee Flask REST API"
  description: "An API about coffee"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Coffee:
      type: "object"
      required:
        - name
        - roaster
        - origin
        - variety
        - process
      properties:
        name:
          type: "string"
        roaster:
          type: "string"
        origin:
          type: "array"
        variety:
          type: "array"
        process:
          type: "array"
        altitude:
          type: "string"
        tasting:
          type: "array"
  parameters:
    name:
      name: "name"
      description: "The coffee name to lookup"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /coffees:
    get:
      operationId: "coffees.read_all"
      tags:
        - Coffees
      summary: "Read the list of coffee"
      responses:
        "200":
          description: "Successfully read the coffee list"
    post:
      operationId: "coffees.create"
      tags:
        - Coffees
      summary: "Create a coffee"
      requestBody:
          description: "coffee to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "coffee"
                $ref: "#/components/schemas/Coffee"
      responses:
        "201":
          description: "Successfully created coffee"
  /coffees/{name}:
    get:
      operationId: "coffees.read_one"
      tags:
        - Coffees
      summary: "Read one coffee"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully read coffee"
    put:
      tags:
        - Coffees
      operationId: "coffees.update"
      summary: "Update a coffee"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully updated coffee"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "coffee"
              $ref: "#/components/schemas/Coffee"
    delete:
      tags:
        - Coffees
      operationId: "coffees.delete"
      summary: "Delete a coffee"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "204":
          description: "Successfully deleted coffee"